// <auto-generated />
using CreditDataHub.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditDataHub.API.Migrations
{
    [DbContext(typeof(CreditDataContext))]
    [Migration("20251006044954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Core.Entities.CustomerProfileEntity", b =>
                {
                    b.Property<string>("SSN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CreditHistoryYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Income")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentHistoryJson")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("SSN");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
